### ISSUE TITLE
Airthings plus is not found on Rpi 4 64 bit version og hassion 

### ISSUE THREAD

**Issue by goegsig** [custom-components/sensor.airthings_wave#29]
I cant get the software to find the Device. It keeps shrowin errors in the log file. 

2020-08-26 22:41:49 ERROR (SyncWorker_11) [custom_components.airthings_wave.airthings] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 177, in get_info
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to 00:81:f9:f0:5c:f9 after 3 seconds.

020-08-26 22:41:53 ERROR (SyncWorker_11) [custom_components.airthings_wave.airthings] Failed to discover sensors
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 197, in get_sensors
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to 00:81:f9:f0:5c:f9 after 3 seconds.

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.3
supervisor | 235
timezone | Europe/Copenhagen
version | 0.114.4
virtualenv | false

  - platform: airthings_wave
    scan_interval: 120
    mac: 00:81:f9:f0:5c:f9

I have tried with mac address and without. Any suggestions?

**Comment by MartyTremblay** [comment]
Hi @goegsig, let's see if we can figure this out.

Nothing particularly pops out from the logs and your setup is typical. How far away is your Pi from the Wave? BLE has a practical range of 2-3 metres at best.

**Comment by goegsig** [comment]
I have moved to the same room 2 meters in distance. The result is the same. From my iphone  the is no truble connecting to teh airwave plus

**Comment by goegsig** [comment]
From a differnt rpi ican connec

root@raspberrypi:~/waveplus-reader#  sudo python2 read_waveplus.py 2930003730 60

Press ctrl+C to exit program

Device serial number: 2930003730
╭──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────╮
│   Humidity   │ Radon ST avg │ Radon LT avg │ Temperature  │   Pressure   │  CO2 level   │  VOC level   │
├──────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────┤
│     63.0 %rH │    176 Bq/m3 │     51 Bq/m3 │   21.36 degC │  1004.56 hPa │    592.0 ppm │    123.0 ppb │
│     63.0 %rH │    176 Bq/m3 │     51 Bq/m3 │   21.36 degC │  1004.56 hPa │    592.0 ppm │    123.0 ppb │

**Comment by MartyTremblay** [comment]
gotcha. guessing that `read_waveplus.py` works on Pi #1 as it does on Pi #2?

**Comment by goegsig** [comment]
I dont know how to test the read_waveplus.py from HassOS 4.12. Dosent look like there is pyton on the host aplication. But is in one of the dockers containers. hosting homeassistent
