### ISSUE TITLE
Airthings Plus with Raspberry Pi 4 initial setup failure

### ISSUE THREAD

**Issue by grosen** [custom-components/sensor.airthings_wave#31]
Initial Setup failing, despite BLE sensor working with MiFlora component. 

Log:
2020-09-15 14:55:39 ERROR (SyncWorker_0) [custom_components.airthings_wave.sensor] Failed intial setup.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] I/O error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 342, in scan
    scan.expect('foooooo', timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 340, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0xaef838e0>
command: /usr/bin/hcitool
args: ['/usr/bin/hcitool', '-i', 'hci0', 'lescan']
buffer (last 100 chars): b''
before (last 100 chars): b'Set scan parameters failed: I/O error\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 279
child_fd: 17
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'foooooo')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 142, in setup_platform
    num_devices_found = airthingsdetect.find_devices()
  File "/config/custom_components/airthings_wave/airthings.py", line 156, in find_devices
    devices = self.adapter.scan(timeout=3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 353, in scan
    raise BLEError(message)
pygatt.exceptions.BLEError: Unexpected error when scanning: Set scan parameters failed: I/O error

**Comment by MartyTremblay** [comment]
This could be related to #32

**Comment by grosen** [comment]
fwiw - unlike issue #32, I have the devices show up in HA (seemingly finds the MAC address and has an initial value for a second), but just shows unavailable for the value. 

Anything to try to fix @MartyTremblay? Thanks!

**Comment by grosen** [comment]
I also manually set the mac address and it stops throwing an error but still doesn't work
anything else to try @MartyTremblay

**Comment by hirofairlane** [comment]
I got the airthings wave to work with latest Hassio 32bit latest version and rpi4, it took like 40 minutes to get the readings, but it started working fine without setting the MAC address.

But each time that I unplug the rpi, or after a power failure the integration starts to show "unavailable" and takes some time to work again, Yesterday it took overnight.

**Comment by hirofairlane** [comment]
I post just in case it would help somebody

After a whole day returning "unavailable", the integration came back to work after a simple:
Configuration>Server Management>Restart
