### ISSUE TITLE
All entities are unavailable in Home Assistant

### ISSUE THREAD

**Issue by captainnapalm** [custom-components/sensor.airthings_wave#35]
Not sure if there's somewhere I can grab logs for this, but I've found this to be quite unreliable, with most of the entities showing up as unavailable a lot of the time. This is particularly unfortunate as I'm using the temperature value in automations in my office.

**Comment by frankvanrad** [comment]
Same here, but have narrowed it down to the .118 upgrade. When I restore to a .117 snapshot it goes back to working fine. I haven't spent enough time looking at the release notes to figure out what broke it.

**Comment by captainnapalm** [comment]
I found the relevant log entry in Home Assistant (I think):

```
Logger: custom_components.airthings_wave.sensor
Source: custom_components/airthings_wave/airthings.py:156
Integration: airthings_wave (documentation)
First occurred: November 28, 2020, 11:27:32 AM (1 occurrences)
Last logged: November 28, 2020, 11:27:32 AM
Failed intial setup.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 342, in scan
    scan.expect('foooooo', timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 340, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0xa96b9760>
command: /usr/bin/hcitool
args: ['/usr/bin/hcitool', '-i', 'hci0', 'lescan']
buffer (last 100 chars): b''
before (last 100 chars): b'Set scan parameters failed: I/O error\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 297
child_fd: 67
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'foooooo')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 142, in setup_platform
    num_devices_found = airthingsdetect.find_devices()
  File "/config/custom_components/airthings_wave/airthings.py", line 156, in find_devices
    devices = self.adapter.scan(timeout=3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 353, in scan
    raise BLEError(message)
pygatt.exceptions.BLEError: Unexpected error when scanning: Set scan parameters failed: I/O error
```

**Comment by lymanbuttler** [comment]
Issue still affects Home Assistant 2020.12.0. I'm getting a very similar log to the above. Gatttool seems to be the problem.

**Comment by mindtripper** [comment]
I did a test downgrading pygatt from 4.0.5 to 4.0.4 inside my HA docker container.
Using `pip install --upgrade pygatt=4.0.4`
Solved my AirThings issue. Have no idea if something else has broke though :)

**Comment by cmartin81** [comment]
Same error here also. Any update on this issue?

**Comment by gaupe75** [comment]
With the latest update (2.8), I got the readings back again.
