### ISSUE TITLE
Can't connect to Airthings Wave+

### ISSUE THREAD

**Issue by darwinsfoot** [custom-components/sensor.airthings_wave#41]
Running on a new install of Home Assistant on Raspberry Pi 4, can't connect.

Getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 211, in get_sensors
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to 80:6F:B0:39:49:2C after 3 seconds.
```

I can connect in the Terminal with bluetoothctl, and also from my phone.
Distance between the Pi and tthe Wave+ is 2.5 meters, line of sight with no obstructions.

Any idea how to debug?

**Comment by darwinsfoot** [comment]
Setting the timeout to 60 seconds gives the same error

**Comment by darwinsfoot** [comment]
Disabling Bluetooth on my phone made it work - although I'm not sure why?

Connection is spotty, but that is BLE I guess...

**Comment by altaic** [comment]
I get hundreds of log entries like this and the connection to my airthings wave+ is very spotty. However, even with the wave+ close to my home assistant machine, it's still bad. Something is amiss in this software or upstream in `pygatt`.

**Comment by altaic** [comment]
I ended up just reducing the verbosity of the logs by changing `_LOGGER.exception("Failed to discover sensors")` to `_LOGGER.error("Failed to discover sensors")` and `_LOGGER.exception("Failed to connect")` to `_LOGGER.error("Failed to connect")` in `airthings.py`.

I still would like to know why the connection is so unstable, but at least my logs aren't getting spammed with backtraces.
