### ISSUE TITLE
Connection time out when restarting

### ISSUE THREAD

**Issue by v1kke** [custom-components/sensor.airthings_wave#46]
Hi,

This is such a great integration and it very eases to connect Airthings Wave. However, there is one issue bugging that I'm facing every now and then in the device discovery when restarting the hass.io instance running on RPi4. The connection time out seems to be too quick and the device doesn't get connected. The workaround for this is to repeat the boot as many times as necessary, sometimes it requires 10 times or so. Is there a possibility to make the discovery time as a variable or increase the discovery time or increase the number or times the discovery is conducted to reduce the risk of failure? Would it be possible to continue the device discovery until connected? Might be that I'm looking a wrong place to resolve this issue though.. any other suggestions?

There is like 6 m in between the RPi4 and AT devices and a kitchen wall which might cause interference. Anyway, the integration works like a swiss clock once connected.

Log says as follows:

2021-03-08 23:08:54 ERROR (SyncWorker_0) [pygatt.backends.gatttool.gatttool] Timed out connecting to A4:DA:32:14:13:5A after 3 seconds.
2021-03-08 23:08:54 ERROR (SyncWorker_0) [custom_components.airthings_wave.airthings] Failed to connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 230, in get_sensor_data
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to A4:DA:32:14:13:5A after 3 seconds.

**Comment by lymanbuttler** [comment]
I get the same errors occasionally on RPi3 running hass.io, but not nearly as often as OP, and when I do it typically resolves after one restart.

Thanks for sharing this integration--saved me $thousands in radon mitigation contract work by letting me solve the problem with Home Assistant instead.

**Comment by marsin-crypto** [comment]
I think I have something that can fit in this category
Using RPi4

Log below:

Logger: custom_components.airthings_wave.airthings
Source: custom_components/airthings_wave/airthings.py:230
Integration: airthings_wave (documentation, issues)
First occurred: March 11, 2021, 10:40:47 PM (107 occurrences)
Last logged: 12:55:02 PM

Failed to connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 230, in get_sensor_data
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to 04:EE:03:D3:DF:85 after 3 seconds.
