### ISSUE TITLE
MAC Address issue

### ISSUE THREAD

**Issue by Delgnelm** [custom-components/sensor.airthings_wave#61]
Hi,

It look like I have an issue with the MAC Address, and the YAML catch it like an interger...

Here is how the YAML  (had to put a screenshot for the color):

```
devices:
  - mac: d8:**:**:**:**:20
    name: ****
refresh_interval: 150
retry_count: 10
retry_wait: 3
log_level: DEBUG
mqtt_discovery: 'true'
```
![image](https://user-images.githubusercontent.com/92599246/144759444-5aa7869f-e76a-482e-83ae-c13018bca75b.png)

I've past several hours searching on google for this issue, but didn't find a method to pass it normally... I try simple and double quote, no success, each time the YAML comes back as show on the screenshot.

Hence here is my error message on Debug mode... Don't know if someone have a better understanding of my issue...

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:48:35] INFO: Getting mqtt configuration...
[13:48:35] INFO: Starting python script...
INFO:airthings-mqtt-ha:Setting up Airthings sensors...
DEBUG:airthings-mqtt-ha:Getting info about device(s)...
ERROR:airthings:Disconnected
Traceback (most recent call last):
  File "/src/airthings.py", line 228, in get_info
    char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected
WARNING:airthings-mqtt-ha:Unexpected exception while getting device information on attempt 1. Retrying in 3 seconds.
```

Thanks !

**Comment by sverrham** [comment]
It sounds like you are concerned that the last number in your mac is highlighted as an integer, this is just your editor highlighting it nothing else I would guess, not an issue,

**Comment by Delgnelm** [comment]
Hi Sverre,

Thanks for your reply.

I retry without providing MAC addresses in the configuration.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:07:49] INFO: Getting mqtt configuration...
[15:07:49] INFO: Starting python script...
WARNING:airthings-mqtt-ha:Invalid mac address provided: 
INFO:airthings-mqtt-ha:Setting up Airthings sensors...
INFO:airthings-mqtt-ha:No devices provided, so searching for Airthings sensors...
INFO:airthings-mqtt-ha:Starting search for Airthings sensors...
INFO:airthings-mqtt-ha:Found 1 airthings device(s).
---------------------------------
Suggested configuration is below:
 
devices:
  - mac: d8:**:**:**:**:20
    name: Insert Device Name
refresh_interval: 150
retry_count: 10
retry_wait: 3
log_level: INFO
mqtt_discovery: 'true'
 
---------------------------------
[15:07:56] INFO: Done.
[cmd] ./run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

It's like on a loop, then sometimes I got this:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:09:24] INFO: Getting mqtt configuration...
[15:09:24] INFO: Starting python script...
WARNING:airthings-mqtt-ha:Invalid mac address provided: 
INFO:airthings-mqtt-ha:Setting up Airthings sensors...
INFO:airthings-mqtt-ha:No devices provided, so searching for Airthings sensors...
INFO:airthings-mqtt-ha:Starting search for Airthings sensors...
INFO:airthings-mqtt-ha:Found 0 airthings device(s).
WARNING:airthings-mqtt-ha:No airthings devices found. If the watchdog option is enabled, this addon will restart and try again.
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Then if I copy and paste the "Suggested configuration" I have the same error as my previous post....

I have first installed the Airthings app on my Smartphone and setup the Airthings device with it. 
When trying to use this code, I shut down my cellphone bluetooth, to make sure the Airthings device is available, but I'm stuck with this error and disconnection.

**Comment by MartyTremblay** [comment]
@Delgnelm, looks like you're using a different component and not this one. Your logs are showing that you are using the https://github.com/mjmccans/airthings-mqtt-ha project
