### ISSUE TITLE
Component stopped working on 2021.12.8-ish

### ISSUE THREAD

**Issue by bjornarfjelldal** [custom-components/sensor.airthings_wave#72]
Hi!

On HA 2021.12.8 your otherwise nice component seem to not be working (at least on my environment).

I am on a default Rpi4 supervised install.

Bluetooth BLE still works on other custom components.

No changes has been done on the install or config files before it suddenly stopped working.

I get these three errors in the log:

```

Logger: custom_components.airthings_wave.airthings
Source: custom_components/airthings_wave/airthings.py:203
Integration: airthings_wave (documentation, issues)
First occurred: 24. januar 2022, 14:39:22 (1 occurrences)
Last logged: 24. januar 2022, 14:39:22
Disconnected

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 203, in get_info
    char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected

```

```

Logger: custom_components.airthings_wave.sensor
Source: custom_components/airthings_wave/airthings.py:203
Integration: airthings_wave (documentation, issues)
First occurred: 24. januar 2022, 14:39:22 (1 occurrences)
Last logged: 24. januar 2022, 14:39:22
Failed intial setup.

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 191, in setup_platform
    devices_info = airthingsdetect.get_info()
  File "/config/custom_components/airthings_wave/airthings.py", line 203, in get_info
    char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
AttributeError: 'NoneType' object has no attribute 'getCharacteristics'

```

```


Logger: custom_components.airthings_wave.sensor
Source: custom_components/airthings_wave/airthings.py:204
Integration: airthings_wave (documentation, issues)
First occurred: 24. januar 2022, 14:39:28 (3 occurrences)
Last logged: 24. januar 2022, 14:39:29
Failed intial setup.

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 191, in setup_platform
    devices_info = airthingsdetect.get_info()
  File "/config/custom_components/airthings_wave/airthings.py", line 204, in get_info
    data = char.read()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 370, in _waitResp
    raise BTLEException("Error from bluepy-helper (%s)" % errcode, resp)
bluepy.btle.BTLEException: Error from bluepy-helper (badstate)
```

**Comment by sverrham** [comment]
Hi, I just updated to 2021.12.10 and that works fine with the latest integration.

**Comment by bjornarfjelldal** [comment]
Thanks for your reply! I am on 2021.12.10 and its not working, so something wrong with my environment then. In the mean time I tried out the ESPhome component, and it works, so I guess I can rule out the Airthings devices.

**Comment by MartyTremblay** [comment]
If it's worth anything, I just upgraded to 2022.2.0 and it is still working for me.

Dead batteries?

**Comment by sverrham** [comment]
As no other complaints has been received and I nor @MartyTremblay  have any issue I will close this.
