### ISSUE TITLE
Failed Initial setup

### ISSUE THREAD

**Issue by briodan** [custom-components/sensor.airthings_wave#77]
I setup the integration via HACS, edited the config file and restarted the server, getting the following error

Failed intial setup.
Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 212, in setup_platform
    num_devices_found = airthingsdetect.find_devices()
  File "/config/custom_components/airthings_wave/airthings.py", line 210, in find_devices
    advertisements = scanner.scan(timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 797, in start
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)

**Comment by Plampi64** [comment]
I have same issue after latest HA updates. Updated HA os (2022.3.5), HA core (2022.4.1) and Passive BLE monitor (8.6.0) to latest versions. After those, Airthings stopped to work.

Traceback (most recent call last):
File "/config/custom_components/airthings_wave/airthings.py", line 251, in get_info
char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 508, in getCharacteristics
rsp = self._getResp('find')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 362, in _waitResp
raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected
2022-04-11 09:04:33 ERROR (SyncWorker_3) [custom_components.airthings_wave.sensor] Failed intial setup.
Traceback (most recent call last):
File "/config/custom_components/airthings_wave/sensor.py", line 220, in setup_platform
devices_info = airthingsdetect.get_info()
File "/config/custom_components/airthings_wave/airthings.py", line 251, in get_info
char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
AttributeError: 'NoneType' object has no attribute 'getCharacteristics'

**Comment by sverrham** [comment]
Looks like issues with your bluethooth, google it and see if some of the solutions can help you out.
